# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/siamaksade/spring-petclinic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest